spring:
  application:
    name: sqs-service
  main:
    allow-bean-definition-overriding: true

aws:
    accessKeyId: abc
    secretKey: def
    localstack:
      endpoint: http://localhost:4566

my-queue-sqs-consumer:
  url: http://sqs.ap-southeast-1.localhost.localstack.cloud:4566/000000000000/my-queue
  maxNumberOfMessages: 10
  waitTimeSeconds: 3